#!/usr/bin/env bash
# Generate .clangd configuration with dynamic Emscripten paths

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "$SCRIPT_DIR"

# Try to find Emscripten
if command -v emcc >/dev/null 2>&1; then
    # Get Emscripten include paths
    EMSCRIPTEN_INCLUDES=$(emcc -xc -E -v /dev/null 2>&1 |
        grep "^ /" |
        grep -E "sysroot/include$|clang/.*/include$" |
        sed 's/^ *//' |
        sed 's#^#    - "-isystem#' |
        sed 's/$/"/')

    HAS_EMSCRIPTEN=1
    # Get version for informational purposes
    EMCC_VERSION=$(emcc --version | head -n1)
else
    echo "Warning: emcc not found, skipping Emscripten configuration" >&2
    echo "  If you have Emscripten installed, activate it first:" >&2
    echo "  source /path/to/emsdk/emsdk_env.sh" >&2
    EMSCRIPTEN_INCLUDES=""
    HAS_EMSCRIPTEN=0
fi

# Generate .clangd file
cat >.clangd <<'EOF'
# Auto-generated by ./generate_clangd.sh
# DO NOT EDIT - changes will be overwritten
# To customize, edit .clangd.template or generate_clangd.sh

CompileFlags:
  Add:
    - "-Iinclude"
    - "-Isrc"
    - "-std=c11"
    - "-Wall"
    - "-Wextra"
    - "-Wpedantic"
  CompilationDatabase: .
EOF

# Add WebAssembly configuration if Emscripten is available
if [ "$HAS_EMSCRIPTEN" = "1" ]; then
    cat >>.clangd <<EOF

---

# WebAssembly-specific configuration for files in bindings/wasm/
# Emscripten paths auto-detected from: $EMCC_VERSION
If:
  PathMatch: [bindings/wasm/.*]
CompileFlags:
  Add:
    - "-Iinclude"
    - "-Isrc"
    - "-std=gnu11"
    - "-Wall"
    - "-Wextra"
    - "-Wpedantic"
    # Emscripten system includes (auto-detected)
$EMSCRIPTEN_INCLUDES
    - "-DEMSCRIPTEN"
    # WebAssembly target
    - "--target=wasm32-unknown-emscripten"
EOF
fi

echo "✓ Generated .clangd configuration"
if [ "$HAS_EMSCRIPTEN" = "1" ]; then
    echo "  - Emscripten paths auto-detected from: $EMCC_VERSION"
else
    echo "  - Emscripten not available (WebAssembly configuration skipped)"
    echo "  - Run 'source /path/to/emsdk/emsdk_env.sh' and regenerate if needed"
fi
